FROM centos
ARG MLNX=y
ARG CORES=1
ARG DURATION=1m
ENV CORES="${CORES}"
ENV DURATION="${DURATION}"
ENV RESULT_DIR=/tmp/cyclictest
ENV pci_west pci_east vf_driver rt_priority stress_tool cross_numa
USER root
COPY CentOS-rt.repo /etc/yum.repos.d/
RUN yum -y --enablerepo=extras install epel-release which pciutils tmux rt-tests wget
RUN if [ "${MLNX}" == "y" ]; then \
        yum install -y python net-tools git libtool automake gcc gcc-c++ \
               cmake autoconf unzip python-six numactl-devel \
               make kernel-devel \
               libibverbs libibverbs-devel rdma-core-devel; \
        KVER=$(uname -r) && DVER=$(rpm -q kernel-devel | sed -e 's/kernel-devel-//') && \
               mkdir -p /lib/modules/${KVER} && \
               ln -fs /usr/src/kernels/${DVER} /lib/modules/${KVER}/build; \
        cd /root && git clone https://github.com/DPDK/dpdk.git && \
               cd /root/dpdk && git checkout origin/releases && \
               sed -i -r -e 's/(.*MLX5.*)=n/\1=y/' ./config/common_base && \
               make install RTE_SDK=`pwd` T=x86_64-native-linux-gcc \
                    DESTDIR=/root/dpdk && \
               cd /root && install /root/dpdk/bin/testpmd '/usr/local/bin' && \
               rm -rf /root/dpdk && \
               yum -y remove automake gcc gcc-c++ cmake autoconf make \
                      libtool git numactl-devel; \
    else yum -y install dpdk dpdk-tools; \
    fi
RUN yum clean all && rm -rf /var/cache/yum
RUN wget -O /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64
RUN chmod +x /root/dumb-init
COPY start_testpmd_cyclictest.sh /root
RUN chmod 777 /root/start_testpmd_cyclictest.sh
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/start_testpmd_cyclictest.sh"]
