FROM centos:latest
RUN yum -y --enablerepo=extras install epel-release && yum install -y python net-tools git libtool automake gcc gcc-c++ cmake autoconf unzip python-six numactl-devel \
    make libibverbs.x86_64 libibverbs-devel.x86_64 librdmacm librdmacm-devel kernel-devel
RUN KVER=$(uname -r) && DVER=$(rpm -q kernel-devel | sed -e 's/kernel-devel-//') && \
    mkdir -p /lib/modules/${KVER} && ln -fs /usr/src/kernels/${DVER} /lib/modules/${KVER}/build
WORKDIR /root
RUN git clone https://github.com/DPDK/dpdk.git
RUN cd /root/dpdk && git checkout origin/releases && sed -i -r -e 's/(.*MLX5.*)=n/\1=y/' ./config/common_base && \
    make install RTE_SDK=`pwd` T=x86_64-native-linux-gcc
RUN yum -y remove automake gcc gcc-c++ cmake autoconf make libtool git numactl-devel && \
    yum clean all && rm -rf /var/cache/yum
WORKDIR /root/dpdk
ENTRYPOINT exec bash 
