FROM centos
USER root
ENV stress_tool
COPY CentOS-rt.repo /etc/yum.repos.d/
RUN yum -y --enablerepo=extras install epel-release && \
    yum install -y stress-ng rteval && \
    yum clean all && \
    rm -rf /var/cache/yum
RUN wget -O /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64
RUN chmod +x /root/dumb-init
COPY start_stress.sh /root
RUN chmod 777 /root/start_stress.sh
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/start_stress.sh"]
