FROM centos
ARG CORES=1
ARG DURATION=1m
ENV CORES="${CORES}"
ENV DURATION="${DURATION}"
ENV RESULT_DIR=/cyclictest_results
USER root
COPY CentOS-rt.repo /etc/yum.repos.d/
RUN yum -y --enablerepo=extras install epel-release && \
    yum install -y rt-tests && \
    yum clean all && \
    rm -rf /var/cache/yum
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "cyclictest -q -D ${DURATION} -p 99 -t ${CORES} -h 30 -m -n > ${RESULT_DIR}/cyclictest_no_stress_${DURATION}.out"]
