FROM centos
ENV DURATION=1m
ENV RESULT_DIR=/tmp/cyclictest
ENV rt_priority stress_tool
USER root
COPY CentOS-rt.repo /etc/yum.repos.d/
RUN yum -y --enablerepo=extras install epel-release which wget tmux rt-tests stress-ng rteval
RUN yum clean all && rm -rf /var/cache/yum
RUN wget -O /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64
RUN chmod +x /root/dumb-init
COPY start_cyclictest.sh /root
RUN chmod 777 /root/start_cyclictest.sh
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/start_cyclictest.sh"]
