FROM centos
ARG CORES=1
ENV CORES="${CORES}"
USER root
COPY CentOS-rt.repo /etc/yum.repos.d/
RUN yum -y --enablerepo=extras install epel-release && \
    yum install -y stress-ng && \
    yum clean all && \
    rm -rf /var/cache/yum
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "stress-ng --cpu ${CORES} --cpu-load 100 --cpu-method loop"]
