FROM centos

RUN yum -y --enablerepo=extras install epel-release centos-release-scl \
       python \
       wget which \
       net-tools \
       iproute2
RUN wget -O /etc/yum.repos.d/ndokos-pbench-epel-7.repo https://copr.fedorainfracloud.org/coprs/ndokos/pbench/repo/epel-7/ndokos-pbench-epel-7.repo \
       && wget -O /etc/yum.repos.d/pbench.repo http://pbench.perf.lab.eng.bos.redhat.com/repo/yum.repos.d/pbench.repo \
       && yum -y install perl-JSON-XS pbench-agent-internal pbench-sysstat \
       && yum -y install openssh-server openssh-clients openssh && mkdir /var/run/sshd \
       && echo 'root:centos' | chpasswd \
       && sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
       && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd \
       && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N "" \
       && ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N "" \
       && ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N "" \
       && mkdir -p /root/.ssh && chmod 700 /root/.ssh \
       && ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ""
RUN yum clean all && rm -rf /var/cache/yum
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile
ENV PATH="/opt/pbench-agent/util-scripts:/opt/pbench-agent/bench-scripts:${PATH}"
RUN wget -O /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
       && chmod +x /root/dumb-init \
       && yum clean all && rm -rf /var/cache/yum

COPY fix-pbench-register-tool.txt fix-pbench-clear-tools.txt /root/
WORKDIR /root
RUN LINE_NUMBERS=$(sed -n -r '/ssh +\$ssh_opts/=' /opt/pbench-agent/util-scripts/pbench-register-tool) && for LINE in ${LINE_NUMBERS}; do sed -i "$((${LINE} - 1))r fix-pbench-register-tool.txt" /opt/pbench-agent/util-scripts/pbench-register-tool; break; done
RUN LINE_NUMBERS=$(sed -n -r '/ssh +\$ssh_opts/=' /opt/pbench-agent/util-scripts/pbench-clear-tools) && for LINE in ${LINE_NUMBERS}; do sed -i "$((${LINE} - 1))r fix-pbench-clear-tools.txt" /opt/pbench-agent/util-scripts/pbench-clear-tools; break; done
RUN rm -rf fix-pbench-register-tool.txt fix-pbench-clear-tools.txt

EXPOSE 22
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/usr/sbin/sshd", "-D", "-p", "2222"]
