---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config-mlx
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [
        {
            "resourceName": "mlnx_sriov_netdevice",
            "isRdma": true,
            "selectors": {
                 "drivers": ["mlx5_core", "mlx5_ib"]
            }
        }
      ]
    }
