---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config-intel
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                 "drivers": ["i40evf"]
            }
        }
      ]
    }
