#apiVersion: v1
#kind: Pod
#metadata:
#  name: 2cpu-nginx
#spec:
#  containers:
#  - name: nginx
#    image: nginx
#    resources:
#      limits:
#        memory: "200Mi"
#        cpu: "2"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-effort-nginx-deployment
spec:
  replicas: 24 
  selector:
    matchLabels:
      name: best-effort-nginx
  template:
    metadata:
      labels:
        name: best-effort-nginx 
    spec:
      containers:
      - name: best-effort-nginx
        image: nginx
