apiVersion: v1
kind: Pod
metadata:
  name: testpmd 
  annotations:
    k8s.v1.cni.cncf.io/networks: mlnx1, mlnx2
spec:
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: appcntr1 
    image: docker.io/cscojianzhan/mlnx_dpdk
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    - mountPath: /sys
      name: sys
    - mountPath: /dev
      name: dev
    resources:
      limits:
        cpu: 4
        hugepages-1Gi: 2Gi
        memory: 2Gi
      requests:
        cpu: 4
        hugepages-1Gi: 2Gi
        memory: 2Gi
  volumes:
  - name: sys
    hostPath:
      path: /sys 
  - name: dev
    hostPath:
      path: /dev
  - name: hugepage
    emptyDir:
      medium: HugePages

