apiVersion: v1
kind: Pod
metadata:
  name: stress 
spec:
  containers:
  - name: stress 
    image: docker.io/cscojianzhan/stress 
    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
