apiVersion: v1 
kind: Pod 
metadata:
  name: rt-cyclictest 
spec:
  restartPolicy: Never 
  containers:
  - name: cyclictest 
    image: cscojianzhan/rt-cyclictest
    env:
    - name: DURATION
      value: "1h"
    - name: CORE_LIST
      value: "6"
    - name: CORES
      value: "1"
    securityContext:
      #privileged: true
      capabilities:
        add:
          - SYS_NICE
          - SYS_RAWIO
          - IPC_LOCK
    volumeMounts:
    - mountPath: /cyclictest_results
      name: results-volume
    - mountPath: /dev/cpu_dma_latency
      name: cstate
  volumes:
  - name: results-volume
    #emptyDir: {}
    hostPath:
      path: /tmp/k8s_cyclictest_results
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  
